version: '3.3'
services:
  rabbitexp003producer:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      ASPNETCORE_URLS: "http://*:80/"
      RABBIT_URI: "amqp://root:root@rabbitmq:5672"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - '18000:80'
    depends_on:
      - mongo
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
        - rabbit-volume-etc:/etc/rabbitmq/
        - rabbit-volume-data:/var/lib/rabbitmq/
        - rabbit-volume-logs:/var/log/rabbitmq/
    environment:
        RABBITMQ_ERLANG_COOKIE: "EXAMPLECOOKIE"
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root
    ports:
        - "18003:5672"
        - "18004:15672"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: Testt
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
     - "18002:27017"
    volumes:
      - mongo-volume:/data/db
volumes:
  rabbit-volume-etc:
  rabbit-volume-data:
  rabbit-volume-logs:
  mongo-volume: